brand:
  name: My Stellar Blog
  tagline: Ideas, notes and stories
menu:
  items:
    - type: search
    - id: post
      title: Blog
      icon: default:documents
      url: /
      accent: '#1BCDFC'
footer:
  sections:
    - title: Blog
      items:
        - title: Recent posts
          url: /
        - title: Archives
          url: /blog/archives/

profiles:
  wiki_index:
    active_menu: post
  wiki:
    active_menu: post
  notebook_index:
    active_menu: post
  note_index:
    active_menu: post
  note:
    active_menu: post

article:
  listing:
    show_tags: true
  show_reading_time: true

{{visual_style}}
