name: npm-publish

on:
  workflow_dispatch:

permissions:
  id-token: write  # 需要给 GitHub Action 添加 id-token 权限，否则无法生成 OIDC 令牌

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24  # npm CLI 的版本需要在 11.5.1 版本或以上才支持 OIDC
          registry-url: https://registry.npmjs.org

      - name: Publish to npm
        run: npm publish --provenance --access public

      # 不再需要配置 NPM TOKEN
